
  /*
{
  titel: "",
  datum: "YYYY-MM-DD",
  zeit: "XX:XX-XX:XX",
  ort: "",
  beschr: "",
  link: "",
  kosten: "",
  referent: "",
  veranstalter: "",
  kontakt: "",
  region: "",  // basel | zuerich | bern | anderswo
  konzept: false
}
*/

window.EVENTS = [ 
  {
  titel: "Gehstück: Wasser Schiene Asphalt",
  datum: "2026-04-26",
  zeit: "15:00-17:00",
  ort: "Badischer Bahnhof, Basel",
  beschr: "Weniger Verkehr hier heisst mehr Verkehr dort. Man kann diesen Strom nicht verhindern, nur lenken. Mühsam, langsam und teuer bauen wir Kanäle, die bald wieder überlaufen. Wir wehren der Flut, doch bändigen können wir sie nicht. Der Verkehr wächst, das ist seine Natur. Er macht, was er will, und füllt die Strassen und die Köpfe. Verängstigt bauen wir Abflussrinnen, aber er ist stärker als wir. Unsere Verkehrspolitik gehorcht dem Prinzip ‚aktiver Fatalismus'. Dauer ca. 2h. Findet bei jedem Wetter statt.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Benedikt Loderer",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Stadtwanderung: Island Hopping. Auf alten Friedhöfen durch die Stadt",
  datum: "2026-05-10",
  zeit: "10:00-14:00",
  ort: "Elisabethenkirche, Basel",
  beschr: "Freiräume sind in Basel zu einem wesentlichen Teil durch die Umnutzung von Friedhöfen entstanden. Parallel zum Wachstum der Stadt sind die Toten (und der Tod) zusehends vom Zentrum in die Peripherie verdrängt worden. Dieser Entwicklung spüren wir auf einer Rundreise nach, bei der wir die ehemaligen Gottesäcker ausserhalb der Stadtmauern zu Fuss erkunden. Mit einem urbanen «Island Hopping» schaffen wir so ein peripatetisches Design – eine neue, temporäre «Umfriedung» um die Stadt. Dauer ca. 4h. Findet bei jedem Wetter statt.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Patrick Düblin",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: true
},
{
  titel: "Wanderung: pittoresque? Auf den Spuren einer malerischen Reise",
  datum: "2026-06-07",
  zeit: "11:00-16:00",
  ort: "Basel – Birstal",
  beschr: "Wir wandern auf den Spuren von Philippe-Sirice Bridel, der 1789 den vielleicht ältesten Basler Wanderführer verfasste. Gemeinsam mit dem Kunsthistoriker Simon Lindner und dem erfahrenen Wanderführer Hanspeter Preiswerk folgen wir seiner Route vom Stadtrand über Arlesheim ins Birstal. Unterwegs vergleichen wir historische Landschaftsbilder und -beschreibungen mit unseren heutigen Eindrücken und entdecken, wie sich die Landschaft, aber auch unsere Wahrnehmung, im Lauf der Zeit verändert haben. Dauer ca. 5h. Findet bei jedem Wetter statt.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Simon Lindner und Hanspeter Preiswerk",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: true
},
{
  titel: "Buchvernissage: «Das ist keine Lesung.»",
  datum: "2026-06-27",
  zeit: "14:00-15:30",
  ort: "Kannenfeldpark, Basel",
  beschr: "Ein Gehstück ist ein Text, der für das Gehen geschrieben oder adaptiert wurde. Wir feiern das Erscheinen dreier Versuche, ein für das Lesen und Gehen taugliches Format zu finden: Die Natur (Georg Christoph Tobler, 1784), Ein Zimmer für sich allein (Virginia Woolf, 1929) und Hitze Stau (LJVW, 2025). Nach einigen einleitenden Worten wählt jede Teilnehmer*in einen der drei Texte und begibt sich selbständig auf den Weg. Den Abschluss bildet ein gemeinsames Picknick. Dauer ca. 1.5h mit anschliessendem Picknick. Rollstuhlgängig. Ausweichdatum für nasse Tage: 04.07.2026.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Elea Bornand und Léonard Wiesendanger (spaz Verlag)",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: true
},
{
  titel: "Walkshop: Kleine Schule des Spazierens",
  datum: "2026-08-23",
  zeit: "14:00-16:00",
  ort: "Merian Gärten, Basel",
  beschr: "«Spazierengehen ist leicht, aber schwer», schrieb der Autor Sigismund von Radecki um 1950. Was hat es mit dem Spazieren auf sich? Wo kommt es her und wo geht es hin? Diese Fragen erkunden wir unter der Leitung der Spazierkünstlerin Marie-Anne Lerjen bei einem Spaziergang durch die Merian Gärten und deren Umgebung. In diesem Walkshop blicken wir auf die Kulturgeschichte des Spazierens und loten gemeinsam auf spielerische Weise die praktischen Aspekte des Spazierens aus. Dauer ca. 2h. Findet bei jedem Wetter statt.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Marie-Anne Lerjen",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "WALKING – Denken in Bewegung (9.-12. September 2026)",
  datum: "2026-09-11",
  zeit: "",
  ort: "Lokal für Raumbegehung / Hafenareal, Basel",
  beschr: "Für seine dritte Ausgabe kommt WALKING nach Basel. Inspiriert von der Promenadologie (Lucius und Annemarie Burckhardt) rückt die Tagung das Gehen als erkenntnisstiftende Praxis in den Mittelpunkt und bringt Positionen aus Kunst, Philosophie und Sozialwissenschaft zusammen. In Zeiten von Ökokrise, Urbanisierungsdruck und digitaler Raumüberformung stellt sich die Frage: Wie lernen wir neu wahrnehmen? Die Tagung bietet Gelegenheit, WALKING aus künstlerischer, wissenschaftlicher, gestalterischer oder aktivistischer Perspektive zu erleben, mitzugestalten und sich mit Gleichgesinnten auszutauschen. Auftakt am Freitag 11.9. im Lokal für Raumbegehung, Tagung am Samstag und Sonntag 12./13.9. im Hafenareal. Weitere Angaben auf ilea.art/blog.",
  link: "https://ilea.art/blog",
  kosten: "",
  referent: "Violeta Burckhardt und Johannes Hedinger",
  veranstalter: "Lokal für Raumbegehung / ILEA / Studio Erde",
  kontakt: "info@ilea.art",
  region: "basel",
  konzept: false
},
{
  titel: "Nachtspaziergang: Durch die Nacht",
  datum: "2026-10-16",
  zeit: "20:30-22:30",
  ort: "Basel (Treffpunkt wird bekannt gegeben)",
  beschr: "Wir sind angespannt, unsere Muskeln geflext, jederzeit bereit. Bei einem Nachtspaziergang nehmen wir uns den öffentlichen Raum zurück, den viele FLINTA* Personen sonst meiden. Dort, wo wir uns kleinmachen, um nicht aufzufallen, gehen wir bewusst. Wir brechen das ungeschriebene Gesetz, dass sich diejenigen aus der Nacht zurückziehen müssen, die sich potenziell unsicher fühlen. Gemeinsam spazieren wir sichtbar und in kollektivem Widerstand durch die Nacht. Dauer ca. 2h. Findet bei jedem Wetter statt.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Kollektiv Stadtschwarm",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: true
},
{
  titel: "Performance und Gespräch: Re ––– Member Non-Lieux",
  datum: "2026-11-08",
  zeit: "13:00-16:00",
  ort: "Bahnhof SBB, Basel",
  beschr: "Mit über 40 Arbeiten untersuchte das Kunstprojekt «NONLIEUX» (1998) sogenannte Nicht-Orte – Durchgangsräume ohne Identität oder Geschichte. Eine der Performances, «Der Beichtstuhleffekt» von Verena Schwab, fand in einer Basler Strassenbahn statt. Mehr als zwanzig Jahre später steigen Schwab und Mitkuratorin Martina Siegwolf erneut ins Tram: erinnernd, erzählend, fragend. Über die Flüchtigkeit von Performance, über Orte und Nicht-Orte – damals wie heute. Die Mitfahrenden sind eingeladen zuzuhören, mitzudenken und eigene Erfahrungen zu teilen. Nach der Fahrt lädt das Lokal für Raumbegehung ein zu Kaffee, Kuchen und weiterem Gespräch. Dauer ca. 3h. Rollstuhlgängig, soweit es die BVB zulässt. Ein gültiges ÖV-Ticket ist mitzubringen. Findet bei jedem Wetter statt.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Martina Siegwolf und Verena Schwab",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
  {
  titel: "Stadtrundgangfestival Bern (25.–29. März 2026)",
  datum: "2026-03-25",
  zeit: "17:00",
  ort: "Bern (diverse Orte)",
  beschr: "Dritte Ausgabe des Stadtrundgangfestivals Bern: 40 Stadtrundgänge in fünf Tagen (25.–29. März 2026). StattLand und Bern Welcome laden zu zahlreichen Veranstaltungen ein, die Zugänge zu Geschichte(n), Stadt und Natur sowie verschiedenen Lebensrealitäten schaffen. Schwerpunkte sind Zugänglichkeit und Inklusion, darunter ein Rundgang zur Gehörlosengeschichte in Gebärdensprache und Lautsprache. Drei Premieren: «Hände erzählen» (DO 26.3., 17 Uhr), «Alles tanzt» (FR 27.3., 14 Uhr) und «Lebensraum Stadt» (FR 27.3., 17 Uhr). Eröffnung am MI 25.3. um 17 Uhr zwischen Münsterplatz und PROGR, offizielle Eröffnung um 18 Uhr im Lehrer*zimmer im PROGR. Abschluss mit Filmscreening und Diskussion am SO 29.3. um 18 Uhr.",
  link: "https://www.stadtrundgangfestival.ch",
  kosten: "CHF 30 / 20 / 10",
  referent: "",
  veranstalter: "StattLand und Bern Welcome",
  kontakt: "info@stattland.ch",
  region: "bern",
  konzept: true
},
  {
  titel: "Nachtwanderung durch Distributionslandschaften (A1): Kirchberg — Bern Wankdorf",
  datum: "2026-04-15",
  zeit: "ab 23:30",
  ort: "Kirchberg-Alchenflüh (Haltestelle)",
  beschr: "Letzte Etappe der zweiten Saison von San Kellers Nachtwanderungen entlang der Autobahn A1. Seit November 2025 führt die Route in sieben Etappen von Zürich-Seebach nach Bern-Wankdorf. Im Zentrum steht die A1 als Kathedrale der Gegenwart – eine öffentlich finanzierte Infrastruktur, gebaut zur Beschleunigung, längst überholt von digitalen Datenströmen. 19 km durch die Nacht, über Haupt- und Nebenstrassen, Forst- und Landwirtschaftswege, immer möglichst nah entlang der A1. Gestartet wird um 23:30 Uhr beim nächstgelegenen Bahnhof. In den frühen Morgenstunden endet die Etappe an einer Haltestelle des öffentlichen Verkehrs. Keine Anmeldung nötig – die Verbindlichkeit muss von innen kommen. Die Wanderung findet bei jeder Witterung statt. Passende Kleidung und ein Blick auf den Wetterbericht empfohlen.",
  link: "https://nachtwandern.com/",
  kosten: "",
  referent: "San Keller",
  veranstalter: "",
  kontakt: "+41 79 542 49 67",
  region: "anderswo",
  konzept: true
},
  {
  titel: "gehen ruhen ein feuer machen (24h)",
  datum: "2026-03-28",
  zeit: "14:00",
  ort: "Kanton Zürich (genauere Angaben nach Anmeldung)",
  beschr: "lerjentours lädt in diesem Walkshop zum gemeinsamen Unterwegssein im Gehen, im Still Werden und am Feuer sitzen – und kochen. Wir kommen in Bewegung und zur Ruhe, übernachten draussen und gehen in Kontakt mit unseren Sinnen und unserer natürlichen Mitwelt. Start: Samstag 28. März 2026, 14 Uhr. Ende: Sonntag 29. März 2026, 14 Uhr. Anforderungen: ca. 2.5 Stunden wandern mit Gepäck, draussen schlafen unter freiem Himmel. Plätze beschränkt. Weiteres Datum: 16./17. Mai 2026.",
  link: "https://www.lerjentours.ch",
  kosten: "CHF 80 (exkl. Lebensmittel)",
  referent: "Marie-Anne Lerjen",
  veranstalter: "lerjentours",
  kontakt: "info@lerjentours.ch",
  region: "zuerich",
  konzept: true
},
  {
  titel: "Basel an der Aare",
  datum: "2026-03-26",
  zeit: "15:00-16:00",
  ort: "Bergstation Marzilibahn, Bern",
  beschr: "Eine Basler Stadtführung? In Bern?! Das ist ja absurd! Mit «Basel an der Aare» schlendern Sie mit Benedikt Meyer durch die Stadt am Rhein – und das ganz bequem vor der Berner Haustür. Eine aberwitzige Spielerei, ein geistiger Bocksprung, ein stadtführerischer Salto rückwärts. Für alle, die sich drauf einlassen. Dauer 60 Minuten. Reservation erforderlich. Max. 20 Personen. Im Rahmen des Stadtrundgangfestivals Bern.",
  link: "https://stadtrundgangfestival.ch/",
  kosten: "CHF 30 / 20 / 10",
  referent: "Benedikt Meyer",
  veranstalter: "Stadtrundgangfestival Bern",
  kontakt: "",
  region: "bern",
  konzept: true
},
  {
  titel: "Sorgetragend im Stadtraum. Ein experimenteller Wahrnehmungsspaziergang",
  datum: "2026-03-26",
  zeit: "13:00-14:30",
  ort: "Kornhausplatz 18, Bern (vor dem Eingang Kornhausforum)",
  beschr: "Die Wahrnehmung der gebauten Umwelt ist abhängig von individuellen Erfahrungen, der eigenen Sozialisierung und somit auch von Bildung, Kultur, Herkunft, Geschlecht oder Alter. Auf dem Spaziergang wird bewusst, wie unterschiedlich wir die Stadt erleben. Wir erfahren, wie sich der öffentliche Raum anfühlt, wenn wir Care-Arbeit leisten oder selbst auf Fürsorge angewiesen sind. So entwickeln wir ein erweitertes Verständnis vom Stadtraum, bei dem Gender, soziale Gerechtigkeit und Diversität im Zentrum stehen. Dauer 90 Minuten. Reservation erforderlich. Max. 20 Personen. Im Rahmen des Stadtrundgangfestivals Bern.",
  link: "https://stadtrundgangfestival.ch/",
  kosten: "CHF 30 / 20 / 10",
  referent: "Henriette Lutz",
  veranstalter: "Stadtrundgangfestival Bern",
  kontakt: "",
  region: "bern",
  konzept: false
},
  {
  titel: "Filmvorführung: «Barbara Buser – Pionierin der Nachhaltigkeit». Im Anschluss Rundgang",
  datum: "2026-04-19",
  zeit: "10:00-14:00",
  ort: "kult.kino, Basel",
  beschr: "Der Dokumentarfilm zeigt die Architektin Barbara Buser, die das Denken über Baukultur, Wiederverwendung und Kreislaufwirtschaft in der Schweiz entscheidend geprägt hat (Prix Meret Oppenheim 2020). Im Anschluss ist Barbara Buser persönlich vor Ort. Nach einer kurzen Stärkung im Kino begeben wir uns gemeinsam zum Franck-Areal, wo wir Einblicke in den laufenden Transformationsprozess erhalten. Produzent Peter Zwierko begleitet den Rundgang, Léonard Wiesendanger eröffnet zusätzliche Perspektiven im Sinne der Spaziergangswissenschaft. Die Veranstaltung ist als zusammenhängendes Format konzipiert. Anmeldung erforderlich. Begrenzte Platzzahl.",
  link: "https://architekturdialoge.ch",
  kosten: "kostenfrei",
  referent: "Barbara Buser, Peter Zwierko und Léonard Wiesendanger",
  veranstalter: "Architektur Dialoge",
  kontakt: "info@architekturdialoge.ch",
  region: "basel",
  konzept: false
},
  {
  titel: "Filmvorführung: «Asphalte Public». Im Anschluss Stadtspaziergang",
  datum: "2026-04-18",
  zeit: "10:00-13:00",
  ort: "kult.kino, Basel",
  beschr: "Der Dokumentarfilm «Asphalte Public» (77 Min.) eröffnet neue Perspektiven auf den öffentlichen Raum. Am Beispiel des Place de l'Esplanade zeigt der Film, wie Architektur, Stadtplanung und Kunst unseren Alltag prägen. Im Anschluss Stadtspaziergang durch Basel mit Marcel Scheible, der die filmischen Themen mit dem realen Stadtraum verbindet. Produzent Gregor Frei begleitet den Rundgang, Léonard Wiesendanger eröffnet zusätzliche Perspektiven im Sinne der Spaziergangswissenschaft nach Lucius Burckhardt. Die Veranstaltung ist als zusammenhängendes Format konzipiert. Anmeldung erforderlich. Begrenzte Platzzahl.",
  link: "https://architekturdialoge.ch",
  kosten: "kostenfrei",
  referent: "Marcel Scheible, Gregor Frei und Léonard Wiesendanger",
  veranstalter: "Architektur Dialoge",
  kontakt: "info@architekturdialoge.ch",
  region: "basel",
  konzept: false
},
  {
  titel: "Filmische Begegnung: Le Corbusier x Lucius Burckhardt (Kurzfilme)",
  datum: "2026-04-17",
  zeit: "18:00-20:00",
  ort: "kult.kino, Basel",
  beschr: "Zum Auftakt des Architektur-und-Film-Wochenendes zeigen wir den Film «Le Corbusier» von Carlos Vilardebo und stöbern in Kurzfilmen zu Lucius Burckhardt. Le Corbusier nutzte das Medium Film, um seine Visionen von Bewegung und Perspektive lebendig werden zu lassen. Burckhardt entwickelte mit seiner Spaziergangswissenschaft eine Methode, die uns lehrt, unsere Umwelt mit allen Sinnen zu erkunden. Im Anschluss Diskussion im Foyer über die Wirkung dieser Ansätze in heutiger Architekturvermittlung und Stadtforschung. Anmeldung erforderlich. Begrenzte Platzzahl.",
  link: "https://architekturdialoge.ch",
  kosten: "kostenfrei",
  referent: "Marcel Bächtiger und Léonard Wiesendanger",
  veranstalter: "Architektur Dialoge",
  kontakt: "info@architekturdialoge.ch",
  region: "basel",
  konzept: false
},
    {
  titel: "Elsässerstrasse. Wohnen, Leben, Arbeiten an der Elsässerstrasse vom Zollstübli bis zum Badhüsli",
  datum: "2026-04-25",
  zeit: "14:00-16:00",
  ort: "Voltaplatz (unter den neuen Bäumen vor dem Kiosk)",
  beschr: "Von der Grenze bis zum St. Johanns-Tor entdecken wir unter der Führung von Historikerin Claudia Wirthlin gemeinsam Altbekanntes und Neues. Was macht das besondere Flair der Elsässerstrasse aus? Was ist eher schwierig aus unserer Sicht? Welche Zukunft wünschen wir uns? Wir schauen zum Teil hinter verschlossene Türen und gewinnen auf unserem Spaziergang vielleicht sogar neue Ein- und Aussichten. Mit anschliessendem Apéro vom Neutralen Quartierverein St. Johann. Trambillett (Kurzstrecke) benögtigt.",
  link: "https://mozaikzeitung.ch/",
  kosten: "gratis / Kollekte",
  referent: "Claudia Wirthlin",
  veranstalter: "mozaik Quartierzeitung",
  kontakt: "",
  region: "basel",
  konzept: false
},
  {
  titel: "Klybeckstrasse. Trouvaillen auf dem Weg vom Claraplatz zum Klybeckschlösschen",
  datum: "2026-04-18",
  zeit: "14:00-16:00",
  ort: "Vor der Clarakirche (Claraplatz)",
  beschr: "Das Bläsitor und das Klybeckschloss sind längst aus dem Stadtbild verschwunden. Aber entlang der Klybeckstrasse gibt es immer noch viele Spuren der Entwicklung des Unteren Kleinbasels und des Klybecks. Unter Führung der Historikerin Sabine Braunschweig und Hans-Georg Heimann, Präsident des Museums für Chemie- und Migrationsgeschichte. Mit anschliessendem Apéro vom mozaik.",
  link: "https://mozaikzeitung.ch/",
  kosten: "gratis / Kollekte",
  referent: "Sabine Braunschweig und Hans-Georg Heimann",
  veranstalter: "mozaik Quartierzeitung",
  kontakt: "",
  region: "basel",
  konzept: false
},
{
  titel: "Spaziergang mit Gedichten und Musik",
  datum: "2026-03-19",
  zeit: "14:00-16:00",
  ort: "Museum Allschwil – Haus für Kultur und Geschichte, Allschwil",
  beschr: "Gemeinsam gehen wir auf einen topoetischen Spaziergang auf dem ehemaligen Judenweg. Bis Mitte des 19. Jahrhunderts durften Jüdinnen und Juden nicht in Basel wohnen. Viele von ihnen pendelten gezwungenermassen den langen Weg von Hegenheim über die 'Judengasse' am Allschwiler Rosenberg in die Stadt. Victor Saudan verbrachte vor einigen Jahren einige Tage auf diesem Weg und schrieb vor Ort Gedichte. Im experimentellen Schreiben verbindet er Topos und Poesie – Topoesie. Philippe Koerper begleitet den Spaziergang musikalisch. Dauer ca. 90 Min. Wichtig: Pass oder ID mitnehmen! Plätze beschränkt, Reservation empfohlen.",
  link: "https://baslergeschichtstage.ch/events/poetischer-spaziergang-zwischen-allschwil-und-hegenheim/",
  kosten: "CHF 15 / 10",
  referent: "Victor Saudan und Philippe Koerper",
  veranstalter: "Museum Allschwil – Haus für Kultur und Geschichte",
  kontakt: "museumallschwil@allschwil.bl.ch",
  region: "basel",
  konzept: false
},

  {
  titel: "Lesekreis Landschaft: Jenseits des Sichtbaren. Landschaft im Spiegel von Politik und Ästhetik",
  datum: "2026-03-11",
  zeit: "19:00-20:00",
  ort: "Lokal für Raumbegehung",
  beschr: "Jacques Rancière beschreibt das späte 18. Jahrhundert als Anfang einer ästhetischen Revolution, in der Landschaft zum Gegenstand politischer und ästhetischer Debatten wurde. Wir lesen Auszüge, die für eine kritische Wahrnehmung von Landschaft im 21. Jahrhundert produktiv sind. – Der Lesekreis Landschaft ist ein öffentliches Gesprächsformat. Ausgangspunkt sind kurze Textauszüge zu Landschaft, Stadt und Wahrnehmung im 21. Jahrhundert. Im Mittelpunkt steht der gemeinsame Dialog. Jedes Treffen wird von einer anderen Person aus Hochschule, Praxis oder Kultur moderiert. Es wird kein Vorwissen vorausgesetzt, die Textauszüge werden vor Ort gelesen. Die Teilnahme ist unverbindlich, die Gruppe setzt sich jedes Mal neu zusammen.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  referent: "Julia Rüegger",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
    {
  titel: "Auf den Spuren der Basler Dichter Werner Lutz und Rainer Brambach",
  datum: "2026-04-12",
  zeit: "11:00-12:30",
  ort: "bei Anmeldung bekannt gegeben",
  beschr: "Der Spaziergang im Dalbeloch am Rhein folgt Gedichten und Lebensspuren von Lyrikerinnen und Lyrikern. Ausgewählte Texte öffnen poetische, biographische und topografische Räume: Rainer Brambach (1917-1983) und Werner Lutz (1930-2016) lebten und schrieben mit Blick auf den Rhein. Ihre Gedichte treten in Dialog mit Texten von Julia Rüegger (*1994), die den Spaziergang begleitet. Dieser klingt mit einem kurzen Gespräch aus.",
  link: "literaturspur.ch",
  kosten: "CHF 35 / CHF 20",
  referent: "Martina Kuoni und Julia Rüegger",
  veranstalter: "Literaturspur",
  kontakt: "info@literaturspur.ch",
  region: "basel",
  konzept: false
},
  {
  titel: "The Long Way Home. Kollektiver Nachtspaziergang",
  datum: "2026-02-27",
  zeit: "ab 22:00",
  ort: "Tramstation Bahnhof St. Johann",
  beschr: "Das Format wurde 2003 vom Zürcher Künstler San Keller ins Leben gerufen – während eines ganzen Jahres traf er sich einmal im Monat an der New Yorker Grand Central Station mit einer Gruppe von Menschen, um diese zu Fuss nachhause zu bringen. Dieses Format holen wir jetzt nach Basel. Wir treffen uns am 27.02.2026 um 22.00 Uhr bei der Tramstation Bahnhof St. Johann und bringen uns eine nach der anderen nach Hause. In jedem Zuhause wird eine kurze (bei Bedarf längere) Rast eingelegt, um sich aufzuwärmen und eine kleine Stärkung zu sich zu nehmen, bevor es zurück auf die Strasse geht. Eine Anmeldung ist nicht nötig. Wichtig sind warme Kleidung und warme, bequeme Laufschuhe. Ausserdem sollte jede*r Teilnehmer*in bereit sein, in seinem*ihrem Zuhause einen Moment der Gastfreundlichkeit und eine kleine Stärkung zu gewähren – dabei geht es nicht um fancy Wohnorte oder besondere Delikatessen, sondern um basale Regeneration.",
  link: "",
  kosten: "",
  referent: "San Keller und Julia Rüegger",
  veranstalter: "",
  kontakt: "",
  region: "basel",
  konzept: true
},
  {
  titel: "Der Wanderformel auf der Spur",
  datum: "2026-03-22",
  zeit: "11:00-14:00",
  ort: "Gelbes Haus, Via Nova 60, Flims",
  beschr: "Wie unterscheiden sich spazieren und wandern, wurde der Geschäftsleiter der Schweizer Wanderwege mal gefragt. Wandern sei eine bewusste Aktivität, die vorbereitet sein müsse. Die Spazierkünstlerin Marie-Anne Lerjen und der Wanderkurator Beat Gugger packen deshalb je ihren Rucksack. Doch für einmal befinden sich darin vielfältige Anregungen. Gemeinsam machen wir uns in Flims auf den Weg und erkunden fussläufig die Formel fürs Wandern. Herzliche Einladung zum Mitwandern! Eine Exkursion im Rahmen der Ausstellung «Wandern. Eine Ausstellung, die bewegt» des Das Gelbe Haus in Flims (bis 6. April 2026).",
  link: "https://www.dasgelbehausflims.ch/de",
  kosten: "CHF 15 / 10",
  referent: "Marie-Anne Lerjen und Beat Gugger",
  veranstalter: "Das Gelbe Haus",
  kontakt: "info@dasgelbehausflims.ch",
  region: "anderswo",
  konzept: false
},
    {
  titel: "Religion – Natur, Landschaft und Wandern",
  referent: "Prof. Dr. Jürgen Mohn",
  datum: "2023-11-07",
  zeit: "18:15–20:00",
  ort: "Kollegienhaus, Universität Basel",
  beschr: "Vortragsreihe von Prof. Dr. Jürgen Mohn. Anmeldung über die Volkshochschule beider Basel. Kurskosten CHF 100.–; alle Daten: 07.11.23 / 14.11.23 / 21.11.23 / 28.11.23",
  link: "https://www.vhsbb.ch",
  kosten: "CHF 100",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@vhsbb.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Gehen",
  datum: "2023-11-22",
  zeit: "12:30–13:30",
  ort: "Merian Gärten",
  beschr: "Adaption fürs Gehen von Thomas Bernhards Text «Gehen».",
  link: "https://gehstück.ch",
  kosten: "Kollekte",
  veranstalter: "Léonard Wiesendanger",
  kontakt: "info@gehstueck.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Träumereien eines einsamen Spaziergängers",
  datum: "2024-02-23",
  zeit: "14:00–15:00",
  ort: "Ermitage Arlesheim",
  beschr: "Adaption fürs Gehen von Jean-Jacques Rousseaus Text «Träumereien eines einsamen Spaziergängers».",
  link: "https://gehstück.ch",
  kosten: "Kollekte",
  veranstalter: "Léonard Wiesendanger",
  kontakt: "info@gehstueck.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Auch ich habe in Arkadien gelebt",
  datum: "2024-04-05",
  zeit: "18:00–19:00",
  ort: "Merian Gärten",
  beschr: "Adaption fürs Gehen von Ingeborg Bachmanns Text «Auch ich habe in Arkadien gelebt».",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@gehstueck.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Landschaft ist darstellbar / nicht",
  datum: "2024-04-21",
  zeit: "14:00–17:00",
  ort: "Ermitage Arlesheim",
  beschr: "Promenadologie. Kann man den schönsten Ort beschreiben? Welche Landschaft ist darstellbar und welche nicht? U. a. am Beispiel von Caspar David Friedrich. Wissenschaftsspaziergang nach Lucius und Annemarie Burckhardt mit Inputs, ästhetischen Interventionen, Zeit zur Diskussion und Raum zur Wahrnehmung.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Grenzgang",
  referent: "Victor Saudan",
  datum: "2024-05-12",
  zeit: "16:00–17:30",
  ort: "Rodersdorf",
  beschr: "",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Der Spaziergang",
  datum: "2024-05-31",
  zeit: "18:00–19:00",
  ort: "Merian Gärten",
  beschr: "Adaption fürs Gehen von Robert Walser Text «Der Spaziergang».",
  link: "https://gehstück.ch",
  kosten: "Kollekte",
  veranstalter: "Léonard Wiesendanger",
  kontakt: "info@gehstueck.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Workshop. Pilgern in 100 Schritten",
  referent: "Prof. Dr. David Atwood",
  datum: "2024-09-28",
  zeit: "15:00–15:45",
  ort: "Schönthal",
  beschr: "Der Religionswissenschaftler Prof. Dr. David Atwood vermittelt das Thema Pilgern frei, experimentell, religions-promenadologisch. Im Rahmen der Ausstellung des Klosters Schönthal «Der eilige Geist kommt zur Ruhe» von Gerda Steiner und Jörg Lenzlinger.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Gehstück. Reise an den schönsten Ort",
  datum: "2024-09-28",
  zeit: "17:15–18:15",
  ort: "Schönthal",
  beschr: "Wir folgen dem Ironiker Heinrich Heine in die Romantik und reisen mit ihm an den schönsten Ort. Im Rahmen der Ausstellung des Klosters Schönthal «Der eilige Geist kommt zur Ruhe».",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Lesekreis Landschaft: Warum ist Landschaft schön? Die Spaziergangswissenschaft",
  datum: "2024-10-09",
  zeit: "19:00",
  ort: "Lokal",
  beschr: "",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Spaziergang. Der Blick der Städter:in über die Stadtmauern",
  datum: "2024-10-13",
  zeit: "13:00–17:00",
  ort: "Riehen Dorf, Tüllinger Berg, Burg Rötteln",
  beschr: "Wo endet die Stadt, wo beginnt das Land? Wieso sind Burgen schön? Wir nähern uns Themen der Spaziergangswissenschaft – beobachtend, intervenierend, diskutierend. Kein Vorwissen notwendig.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Adaption fürs Gehen. Gehen",
  datum: "2024-11-28",
  zeit: "12:30–13:30",
  ort: "Merian Gärten",
  beschr: "Schnellgang mit dem abgründigen Text «Gehen» von Thomas Bernhard, adaptiert fürs Gehen. Teil der Lesungs- und Entwicklungsreihe «Gehstück, das».",
  link: "https://gehstück.ch",
  kosten: "Kollekte",
  veranstalter: "Léonard Wiesendanger",
  kontakt: "info@gehstueck.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Spaziergang im Stadtverkehr. Zur Geschichte des städtischen Freiraums",
  datum: "2025-02-23",
  zeit: "14:00–16:00",
  ort: "Basel",
  beschr: "Wir spazieren und denken als Spazierende darüber nach, wo wir uns in der Stadt wohl und sicher fühlen – und wo nicht. Die Allmend gehört uns allen. Ist sie so ausgestaltet, dass sie für uns, die zu Fuss unterwegs sind, gut funktioniert? Welche Hindernisse stellen sich uns in den Weg?",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Rettet die Altstadt. Aktion Nadelberg vom 11. März 1961",
  datum: "2025-03-20",
  zeit: "",
  ort: "",
  beschr: "Der Rundgang erinnert an den historischen Fackelzug von 1961 für den Rosshof und beleuchtet zentrale Ereignisse im Kampf um den Erhalt der Basler Altstadt. Auf dem Spaziergang werden prägende Stationen dieser Geschichte besucht: Von der Aktion «Die Altstadt in Gefahr» (1949), bei der Lucius Burckhardt und Markus Kutter gegen den Abbruch der Aeschenvorstadt und die Talentslastungsstraße kämpften, über den Abbruch des Hauses «Sodeck» (1975) bis hin zur Erhaltung des Gerichtsgebäudes. Am Marktplatz wird die wegweisende Abstimmung gegen den Markthof (1976) thematisiert, die einen Wandel im Denken der Bevölkerung einleitete. Über den Spalenberg führt der Rundgang schließlich zum Rosshof und endet mit einer Rückbesinnung auf den Fackelzug sowie die leidenschaftliche Rede von Dr. Rudolf Fellmann.",
  link: "",
  kosten: "kostenlos",
  veranstalter: "UB Ausstellung: Sehend denken",
  kontakt: "",
  region: "basel",
  konzept: false
},
{
  titel: "Gehstück. Reise an den schönsten Ort",
  datum: "2025-03-29",
  zeit: "17:30–19:00",
  ort: "Schönthal",
  beschr: "In der Umgebung des Klosters Schönthal, wo Annemarie und Lucius Burckhardt viel Zeit verbrachten, folgen wir dem Ironiker Heinrich Heine in die Romantik und auf den Brocken, den höchsten Berg Deutschlands. Der Aufstieg ist nicht ohne Tücken, Burckhardts Spaziergangswissenschaft liefert uns das nötige Rüstzeug dazu.",
  link: "https://gehstück.ch",
  kosten: "kostenlos",
  veranstalter: "Léonard Wiesendanger",
  kontakt: "info@gehstueck.ch",
  region: "basel",
  konzept: false
},
{
  titel: "„Religions“-Promenadologie. Wo bitte geht’s denn hier zur Religion?",
  referent: "Prof. Dr. David Atwood",
  datum: "2025-04-04",
  zeit: "16:00–17:15",
  ort: "Basel",
  beschr: "Auf Um- und Abwegen erforschen wir die Religionsgeschichte der Basler Innenstadt und gehen keltischen und römischen, den weithin sichtbaren christlichen und weniger sichtbaren neureligiös-spirituellen Spuren nach.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Tour de Bale (1)",
  referent: "Office for Peripatetic Design",
  datum: "2025-05-18",
  zeit: "10:00",
  ort: "Basel",
  beschr: "Was, wenn eine abstrakte Linie körperliche Form annimmt? In zwei Etappen (1)/(2) schreiten wir die rund 28 km lange Stadtgrenze von Basel ab, konfrontieren uns mit dem Nicht-Vorhersehbaren und loten physische, politische und mentale Grenzen aus.",
  link: "https://www.instagram.com/office.for.peripatetic.design/",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Tour de Bale (2)",
  referent: "Office for Peripatetic Design",
  datum: "2025-05-25",
  zeit: "10:00",
  ort: "Basel",
  beschr: "Was, wenn eine abstrakte Linie körperliche Form annimmt? In zwei Etappen (1)/(2) schreiten wir die rund 28 km lange Stadtgrenze von Basel ab, konfrontieren uns mit dem Nicht-Vorhersehbaren und loten physische, politische und mentale Grenzen aus.",
  link: "https://www.instagram.com/office.for.peripatetic.design/",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Kulturstadtplan. Buchraum Basel",
  datum: "2025-06-12",
  zeit: "",
  ort: "Quartierzentrum Oekolampad",
  beschr: "",
  link: "https://buchraumbasel.ch/kulturstadtplan",
  kosten: "kostenlos",
  veranstalter: "Verein BuchRaumBasel",
  kontakt: "",
  region: "basel",
  konzept: false
},
{
  titel: "Spaziergangswissenschaft trifft Literatur. Lucius und Annemarie Burckhardt mit Robert Walser im Gespräch",
  datum: "2025-09-25",
  zeit: "19:00–20:30",
  ort: "Buchhandlung Labyrinth",
  beschr: "Welche Rolle nimmt das Spazieren im Schaffen von Robert Walser und den Burckhardts ein? Wo berühren sich ihre Ansätze und wo unterscheiden sie sich? Was können wir davon für unser eigenes Gehen mitnehmen?",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Rating Seats",
  datum: "2025-10-12",
  zeit: "14:00–16:00",
  ort: "Basel",
  beschr: "What makes an urban space a good one? We go through the city and explore places to sit, planned or accidental. We take Instax photos and rate the seats. It‘s a slow walk, with plenty of pauses for sitting.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Das Basler Hafenareal in der Entwicklung. Ein städtebauliches Porträt",
  referent: "Hans Baumgartner und Reto Bürgin",
  datum: "2025-10-19",
  zeit: "14:00–16:00",
  ort: "Hafenareal Basel",
  beschr: "Im Basler Hafen entsteht ein neues Quartier, – oder doch ein grosser Freiraum für alle? Das Areal transformiert sich, aus industriell wird urban. Wir fragen nach den Qualitäten des Bestehenden und dem aktuellen Stand der Entwicklung.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "flanör",
  datum: "2025-11-16",
  zeit: "ganzer Tag",
  ort: "jede Stadt",
  beschr: "Wie feiern wir die stillen Erfahrungen der Einzelnen? die sinnlichen Beobachtungen? die feinen Nachdenkereien? die freundschaftliche Anonymität? die unsichtbaren Fäden, die sich um jede Ecke und über jede Strasse spannen? Einladung – Am Sonntag, dem 16. November findet flanör statt. – flanör feiert die städtische Kultur des Gehens und hat keinen bestimmten Ort, nur die Stadt. – Die Idee ist einfach: Eine stille Bewegung wie das Gehen feiert sich vielleicht am besten still, erst recht, wenn so vieles heute so laut um Aufmerksamkeit schreit. – 1. Nimm Dir am 16. November etwas Zeit fürs Gehen in der Stadt. Geh allein, geht zu zweit, oder auch als Gruppe. – 2. Gib diese Einladung an zehn Personen weiter, die gerne zu Fuss unterwegs sind, oder es gerne öfters wären. – Am 16. November werden viele Leute unterwegs sein und voneinander wissen, ohne mehr voneinander zu wissen. – Ein Fest, wie es noch keines gegeben hat! – flanör findet bei jedem Wetter statt. – Diese Einladung erreicht Dich aus Basel. Passe die Signatur [Basel] an, wenn Du die Einladung von woanders weiterleitest.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "anderswo",
  konzept: true
},
{
  titel: "Die unsichtbare Stadt. Italo Calvino",
  datum: "2025-12-13",
  zeit: "16:00–17:30",
  ort: "",
  beschr: "Italo Calvino schreibt mit «Die unsichtbaren Städte» einen Klassiker literarischer Stadtbetrachtung. Wir lesen Passagen und sehen, wie Basel verschwindet und wieder auftaucht.",
  link: "https://lokal-fuer-raumbegehung.ch",
  kosten: "kostenlos",
  veranstalter: "Lokal für Raumbegehung",
  kontakt: "info@lokal-fuer-raumbegehung.ch",
  region: "basel",
  konzept: false
},
{
  titel: "Gespräch in der Bibliothek: Lucius Burckhardt",
  datum: "2025-11-05",
  zeit: "17:00–18:00",
  ort: "FHNW Bibliothek Muttenz, 3. OG",
  beschr: "Gespräch zwischen Dominique Salathé (HABG, Institut Architektur) und Dr. Christian Reutlinger (HSA, Institut Sozialplanung). Moderation: Dieter Kohler.",
  link: "",
  kosten: "kostenlos",
  veranstalter: "FHNW Bibliothek Muttenz",
  kontakt: "",
  region: "basel",
  konzept: false
},
{
  titel: "jane’s walk",
  datum: "2025-05-02",
  zeit: "",
  ort: "alle Städte",
  beschr: "Jane’s Walk ist ein nach Jane Jacobs benannter Nachbarschaftsspaziergang, der jährlich in Hunderten Städten stattfindet. Spaziergänge schaffen Raum für Austausch, Gemeinschaft und Geschichten. Alle könen grundsätzlich einen Spaziergang veranstalten. Die Website janeswalk.org unterstützt bei der Konzeption und Durchführung.",
  link: "https://janeswalk.org/",
  kosten: "kostenlos",
  veranstalter: "",
  kontakt: "",
  region: "basel",
  konzept: false
},
{
  titel: "Schreib-Walk-Shop. Zu den Sternen",
  referent: "Marie-Anne Lerjen",
  datum: "2025-11-13",
  zeit: "18:30–20:00",
  ort: "Zürich",
  beschr: "«Eines nachts, sternklarer Januar, habe ich Vater und Mutter auf die Gürtelsterne von Orion gesetzt, Vaters liebstes Zeichen am Winterhimmel», so schreibt der junge Erzähler in Klaus Merz’ Roman «Jakob schläft» (1997). Der Nachthimmel und insbesondere der Orion spielen eine wichtige Rolle in dieser kurzen Familiengeschichte. Auch am Herbsthimmel über Zürich zeigt sich das Sternbild des Orion. Im Rahmen der Ausstellung «Merz Welt» der Galerie Litar in Zürich lädt lerjentours zu einem Schreib-Walk-Shop, auf dem wir uns auf einem kurzen Abendspaziergang vom Nachthimmel zu Wortfolgen inspirieren lassen. Schreiberfahrung ist für eine Teilnahme nicht notwendig. Es braucht auch keine Kenntnisse von Klaus Merz’ Text.",
  link: "https://www.lerjentours.ch/zu-den-sternen/",
  kosten: "CHF 15 / CHF 10",
  veranstalter: "litar (Ausstellung: Merz Welt)",
  kontakt: "info@litar.ch",
  region: "zuerich",
  konzept: false
},
{
  titel: "WALKING – Denken in Bewegung",
  datum: "2025-09-05",
  zeit: "",
  ort: "Berghotel Alpenblick in Tenna, Safiental",
  beschr: "Eine transdisziplinäre Tagung zu Gehen als künstlerische Praxis, räumliche Erfahrung und erkenntnisstiftende Methode im Geist von Lucius Burckhardt.Organisiert von ILEA - Institute for Land and Environmental Art.Kuration/Moderation: Johannes M. Hedinger, Raimund RodewaldWALKING als Methode und Medium gewinnt in einer fragmentierten Welt neue Bedeutung. Zum 100. Geburtstag von Lucius Burckhardt fragen wir, wie seine Promenadologie heute weitergedacht werden kann – als kritische Praxis der Wahrnehmung, als künstlerische Forschung, als politisches Mittel. Gehen heißt, wahrzunehmen, zu hinterfragen, Raum neu zu schreiben. Künstlerische und wissenschaftliche Positionen greifen Burckhardts Impulse auf und erweitern sie um feministische, dekoloniale und performative Perspektiven. WALKING wird damit zu einer transdisziplinären Praxis: Erkenntnisform, Widerstandsgeste, ästhetische Forschung. Die Frage lautet heute nicht mehr: „Warum ist Landschaft schön?“, sondern: Wie lässt sich in einer komplexen Welt durch Bewegung, Aufmerksamkeit und situatives Denken eine neue Wahrnehmung kultivieren? Versammelt und diskutiert werden Positionen, die sich mit WALKING als erkenntnisstiftender, ästhetischer und politischer Praxis befassen – aus künstlerisch-gestalterischen, wissenschaftlicher oder aktivistischer Perspektive. Es sind auch Formate, die über klassische Vorträge hinausgehen: performative Walks, Lecture Walks, Walkshops, interaktive Settings, Audio- oder Textspuren u.a. Kuration/Moderation: J. M. Hedinger, R. Rodewald.",
  link: "https://ilea.art/",
  kosten: "",
  veranstalter: "ILEA",
  kontakt: "info@ilea.art",
  region: "anderswo",
  konzept: false
},
{
  titel: "Lucius Burckhardt Convention IV",
  datum: "2025-06-27",
  zeit: "",
  ort: "Kunsthochschule Kassel, Hörsaal",
  beschr: "Wir feiern am letzten Wochenende im Juni den 100. Geburtstag des Schweizer Soziologen Lucius Burckhardt. Annemarie (1930–2012) und Lucius Burckhardt (1925–2003) haben mit kritischem Blick und großer Weitsicht auf vielen Gebieten die Wahrnehmung und Gestaltung unserer Welt seit den 1950er Jahren beeinflusst. Vielen Studenten und Studentinnen in Europa – nicht nur in den entwerfenden Berufen – eröffneten sie neue Perspektiven. Beide waren von 1973 bis 1997 an der Universität Kassel im Fachbereich Architektur, Stadtplanung und Landschaftsplanung aktiv. Wer plant die Planung? Warum ist Landschaft schön? Design ist unsichtbar, Durch Pflege zerstört oder Der kleinstmögliche Eingriff: diese Burckhardtschen Fragen und Formeln sind bis heute aktuell. Bereits als Student kämpfte Lucius Burckhardt gegen die Zerstörung der Gotischen Altstadt von Basel, die dem autogerechten Umbau weichen sollte. In den 1980er Jahren sprechen die Burckhardts von der Spaziergangswissenschaft ...",
  link: "https://www.lucius-burckhardt.org/Deutsch/Convention/4.Convention.html",
  kosten: "kostenlos",
  veranstalter: "Prof. Martin Schmitz",
  kontakt: "",
  region: "anderswo",
  konzept: false
}
  ];